name: 'Run Tests'

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.can-fail }}
    strategy:
      fail-fast: true
      matrix:
        php: ['7.4', '8.0', '8.1', '8.2']
        symfony: ['4.4.*', '5.4.*', '6.0.*', '6.1.*', '6.2.*', '6.3.*']
        composer-flags: ['--prefer-stable']
        can-fail: [false]
        with-twig: [true]
        include:
          # Run "no Twig" build on latest PHP and Symfony LTS
          - php: '8.1'
            symfony: '5.4.*'
            composer-flags: '--prefer-stable'
            can-fail: false
            with-twig: false
          - php: '7.4'
            symfony: '4.4.*'
            composer-flags: '--prefer-stable --prefer-lowest'
            can-fail: false
            with-twig: true
        exclude:
          - php: '7.4'
            symfony: '6.0.*'
          - php: '7.4'
            symfony: '6.1.*'
          - php: '7.4'
            symfony: '6.2.*'
          - php: '7.4'
            symfony: '6.3.*'
          - php: '8.0'
            symfony: '6.1.*'
          - php: '8.0'
            symfony: '6.2.*'
          - php: '8.0'
            symfony: '6.3.*'
          - php: '8.2'
            symfony: '4.4.*'

    name: "PHP ${{ matrix.php }}${{ matrix.with-twig == false && ' - Without Twig' || '' }} - Symfony ${{ matrix.symfony }}${{ matrix.composer-flags != '' && format(' - Composer {0}', matrix.composer-flags) || '' }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.composer/cache/files
          key: dependencies-symfony-${{ matrix.symfony }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}-flags-${{ matrix.composer-flags }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2,flex
          extensions: curl, iconv, mbstring, pdo, pdo_sqlite, sqlite, zip
          coverage: none

      - name: Remove Twig
        if: matrix.with-twig == false
        run: |
          composer remove --dev --no-update pagerfanta/twig symfony/twig-bridge symfony/twig-bundle twig/twig

      - name: Install dependencies
        run: |
          composer update ${{ matrix.composer-flags }} --prefer-dist
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}

      - name: Execute tests
        run: vendor/bin/phpunit
